[package]
name = "solana-dao-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
# 序列化（基础功能）
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# 异步运行时
tokio = { version = "1.0", features = ["full"] }

# 日志
env_logger = "0.10"
log = "0.4"
